param(
    [Parameter(Mandatory = $true)]
    [string]$RepoRoot,

    [ValidateSet("Update", "Check")]
    [string]$Mode = "Update"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$RepoRoot = (Resolve-Path $RepoRoot).Path
$toolRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Import-Module (Join-Path $toolRoot "AiCodeMap.IO.psm1") -Force
Import-Module (Join-Path $toolRoot "AiCodeMap.Model.psm1") -Force
Set-AiCodeMapIoRoot $RepoRoot
Set-AiCodeMapModelRoot $RepoRoot

$configPath = Join-Path $RepoRoot ".agent\code-map\config.json"
$currentRoot = Join-Path $RepoRoot ".agent\code-map\current"
$workRoot = Join-Path $RepoRoot "out\ai-code-map"
$generatedRoot = Join-Path $workRoot "generated"
$statePath = Join-Path $workRoot "state.json"

if (-not (Test-Path $configPath)) { throw "AI code map config is missing: $configPath" }
$config = Get-Content $configPath -Raw | ConvertFrom-Json
$inputHash = Get-AiInputFingerprint

if ($Mode -eq "Update" -and (Test-Path $statePath) -and (Test-Path (Join-Path $currentRoot "INDEX.json"))) {
    $state = Get-Content $statePath -Raw | ConvertFrom-Json
    $currentOutputHash = Get-AiDirectoryFingerprint $currentRoot
    if ($state.input_hash -eq $inputHash -and $state.output_hash -eq $currentOutputHash) {
        Write-Host "AI code map: up to date"
        exit 0
    }
}

if (Test-Path $generatedRoot) { Remove-Item $generatedRoot -Recurse -Force }
[IO.Directory]::CreateDirectory((Join-Path $generatedRoot "modules")) | Out-Null
$moduleMaps = @(Get-AiModuleMaps)

foreach ($map in $moduleMaps) {
    Write-AiStableJson (Join-Path $generatedRoot "modules\$($map.module).json") $map
}

$indexModules = @($moduleMaps | ForEach-Object {
    [ordered]@{
        module = $_.module
        kind = $_.kind
        responsibility = $_.responsibility
        map = "modules/$($_.module).json"
        dependencies = @($_.observed.dependencies)
        tests = @($_.declared.tests)
        skills = @($_.declared.skills)
    }
})
Write-AiStableJson (Join-Path $generatedRoot "INDEX.json") ([ordered]@{
    schema_version = 1
    current_phase = [string]$config.current_phase
    build_entrypoint = [string]$config.canonical_build_entrypoint
    modules = $indexModules
})

$context = @(
    "# A-Engine AI Context", "",
    "> Generated by build.bat. Do not edit generated files directly.", "",
    "Current phase: **$($config.current_phase)**", "",
    "Build/test entrypoint: **$($config.canonical_build_entrypoint)**", "",
    "## Navigation rules"
)
foreach ($rule in @($config.rules)) { $context += "- $rule" }
$context += @("", "## Modules")
foreach ($map in $moduleMaps) {
    $deps = if (@($map.observed.dependencies).Count) { @($map.observed.dependencies) -join ", " } else { "none" }
    $context += @(
        "", "### $($map.module)", "$($map.responsibility)", "",
        "- Map: modules/$($map.module).json",
        "- Dependencies: $deps",
        "- Tests: $(@($map.declared.tests) -join ', ')",
        "- Skills: $(@($map.declared.skills) -join ', ')",
        "- Entry points: $(@($map.declared.entry_points) -join ', ')"
    )
}
Write-AiUtf8 (Join-Path $generatedRoot "AI_CONTEXT.md") (($context -join "`n") + "`n")

if ($Mode -eq "Check") {
    $differences = Compare-AiGeneratedDirectory $generatedRoot $currentRoot
    if ($differences.Count -gt 0) {
        Write-Host "AI code map drift detected:" -ForegroundColor Red
        $differences | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
        Write-Host "Run .\build.bat map and commit generated map changes." -ForegroundColor Yellow
        exit 3
    }
    Write-Host "AI code map: committed snapshot matches source"
    exit 0
}

$changeCount = Sync-AiGeneratedDirectory $generatedRoot $currentRoot
$outputHash = Get-AiDirectoryFingerprint $currentRoot
[IO.Directory]::CreateDirectory($workRoot) | Out-Null
Write-AiStableJson $statePath ([ordered]@{ input_hash = $inputHash; output_hash = $outputHash })
Write-Host "AI code map: updated $changeCount file(s)"
exit 0
