name: windows-x64

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  foundation:
    runs-on: [self-hosted, windows, x64]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Configure, build, and test
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do call "%%i\Common7\Tools\VsDevCmd.bat" -arch=x64 -host_arch=x64
          cmake --preset windows-x64-debug
          cmake --build --preset windows-x64-debug --parallel
          ctest --preset windows-x64-debug
